#!/bin/bash

 cd ~/
rm Lucien*
echo 'Files generated by astral deleted'

cd ~/AssignmentMPI/
rm  *.csv
echo 'CSV files deleted'

cd ~/AssignmentMPI/SerieCPP/
rm *.o
rm main
echo 'Files generated because of the linkage deleted'

cd ~/AssignmentMPI/ParallelC/
rm analytic explicit implicit crank
echo 'Exe generated by the compilation are deleted'
